- name: Install JunOS
  hosts: ssw1.pit1
  serial: 1
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  vars:
   pkg_dir: /tftpboot/juniper/
   OS_version: 17.4R2.4
   OS_package: jinstall-host-qfx-10-f-flex-x86-64-17.4R2.4-secure-signed.tgz
   log_dir: /var/log/ansible
   netconf:
    host: "{{ inventory_hostname }}"
    username: databank
    

  tasks:

  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Install JunOS Software
    junos_install_os:
     user=databank
     host={{ inventory_hostname }}
     version={{ OS_version }}
     reboot=yes
     package={{ pkg_dir }}/{{ OS_package }}
     logfile={{ log_dir }}/software.log
    register: sw
    notify:
    - wait_reboot
    - send mail

  handlers:

  - name: wait_reboot
    wait_for: host={{ inventory_hostname }} port=830 timeout=3600
    when: not sw.check_mode

  - name: send mail
    mail:
     subject: Firmware Upgrade of {{ inventory_hostname }} Complete
     body: ' Automated upgade of {{ inventory_hostname }} is complete.
     Firmware has been upgraded to: {{ OS_version }}'
     to: zgould@databank.com

